spring.data.mongodb.uri=mongodb://localhost:27017/user-security
server.port= 8089

spring.application.name= securityserver
#
#eureka.instance.lease-renewal-interval-in-seconds=1
#eureka.instance.lease-expiration-duration-in-seconds=2

#eureka.client.serviceUrl.defaultZone= http://localhost:8761/eureka/
#eureka.client.healthcheck.enabled=true
#
#spring.main.allow-circular-references=true
#logging.level.com.example: DEBUG

zuul.routes.product-service.url=http://localhost:8081
zuul.routes.inventory-service.url=http://localhost:8083
zuul.routes.order-service.url=http://localhost:8082