spring.data.mongodb.uri=mongodb://localhost:27017/inventory-service

server.port=8083
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
spring.application.name=inventory-service
